# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='brief',
            field=models.CharField(blank=True, max_length=200, verbose_name='\u6458\u8981'),
        ),
    ]
