# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_auto_20171018_0732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='auth',
            field=models.CharField(max_length=100),
        ),
    ]
