# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-18 12:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20171018_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='point_good',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='article',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
