# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-27 10:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0006_article_views'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='brief',
            new_name='excerpt',
        ),
    ]
