# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-31 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0007_auto_20171027_1046'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='point_good',
        ),
        migrations.RemoveField(
            model_name='article',
            name='view_count',
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=10000, verbose_name='\u6807\u9898'),
        ),
    ]
