# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 08:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gustbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='words_board',
            name='publish',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
