# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-09-09 14:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artical',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('main_body', models.TextField()),
                ('distribute_date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Author_massage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('join_date', models.DateField()),
                ('self_introduce', models.CharField(max_length=240)),
            ],
        ),
        migrations.AddField(
            model_name='artical',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.Author_massage'),
        ),
    ]
