# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 06:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20170913_1822'),
    ]

    operations = [
        migrations.CreateModel(
            name='Words_board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('publist', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
