# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-10-01 07:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_words_board'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Words_board',
        ),
    ]
